# Generated by Django 5.1.3 on 2024-12-07 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_donate_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='App.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_requests', to='App.register'),
        ),
    ]
