# Generated by Django 5.1.3 on 2024-12-07 11:25

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_request_user_alter_request_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
