# Generated by Django 5.1.3 on 2024-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_request_created_at_remove_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='blood_group',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
