# Generated by Django 5.1.3 on 2024-12-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_register_blood_group_alter_register_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AlterField(
            model_name='register',
            name='blood_group',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.register'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(max_length=15),
        ),
    ]
